In [5]:
import sys
!{sys.executable} -m pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [4]:
import sys
print(sys.executable)

c:\Users\darks\anaconda3\envs\retail_analytics\python.exe

In [8]:
import pandas as pd
df = pd.read_excel(r"C:\Users\darks\Downloads\ML_6_Month_Roadmap_Tracker_2(1).xlsx")
df

,Date,Week,Day,Category,Topic / Task,Learning Outcome,Status,Priority,Hours Planned,Hours Spent,Resources,Deliverable,Notes,Reviewed,Next Action
0,2026-08-01,1.0,1.0,Python Fundamentals,"Object-oriented Python basics (classes, methods).",To be familiarized in python oop,Completed,NaN,2hr,1hr,https://youtu.be/rLyYb7BFgQI?si=4rjWdFSmoYcEUIrI,Documented class examples on Github,studied pythons classes andmethods,Nop,would need to learn more oop basics more than ...
1,2026-08-02,1.0,2.0,Python Fundamentals,"Python libraries intro (NumPy arrays, basic ops).",To be familiar in Python Library Numpy,Completed,NaN,4hr,2.5hrs,https://youtu.be/QUT1VHiLmmI?si=esVkANOrESh59ySI,"Numpy array manipulations (slicing, linear alg...",basic familiarity with numpy,nop,will need to understand or implement numpy in ...
2,2026-08-03,1.0,3.0,Python Fundamentals,"Pandas introduction: DataFrames, reading CSV",To be familiar in pandas,Not Started,NaN,5hr,NaN,https://youtu.be/Mdq1WWSdUtw?si=lwgel5tRZxhlcqhJ,"Load a sample dataset (Iris or\nTitanic), per...",NaN,NaN,NaN
3,2026-08-04,1.0,4.0,Algorithm,Write\nrecursive and iterative functions for c...,Brushing up recursion,Not Started,NaN,1hr,NaN,https://youtu.be/ivl5-snqul8?si=jFyy8k2glNd60W6M,do a easy and medium question in this,NaN,NaN,NaN
4,2026-08-04,1.0,4.0,SQL,"Advanced SQL (GROUP BY, aggregations, subqueries)",To be able to understand Advanced sql queries,Not Started,NaN,4hr - 6hrs,NaN,https://youtu.be/VQf0V6Wwbf4?si=M7Uwn8VnZeDFw1...,Questions in MODE ANALYTICS,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178,NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
pd.set_option('display.max_rows', None)

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              17 non-null     datetime64[us]
 1   Week              17 non-null     float64
 2   Day               17 non-null     float64
 3   Category          15 non-null     str
 4   Topic / Task      15 non-null     str
 5   Learning Outcome  10 non-null     str
 6   Status            180 non-null    str
 7   Priority          0 non-null      float64
 8   Hours Planned     14 non-null     str
 9   Hours Spent       2 non-null      str
 10  Resources         13 non-null     str
 11  Deliverable       14 non-null     str
 12  Notes             2 non-null      str
 13  Reviewed          2 non-null      str
 14  Next Action       2 non-null      str
dtypes: datetime64[us](1), float64(3), str(11)
memory usage: 27.3 KB

In [17]:
df.shape

(180, 15)

In [18]:
df.tail()

,Date,Week,Day,Category,Topic / Task,Learning Outcome,Status,Priority,Hours Planned,Hours Spent,Resources,Deliverable,Notes,Reviewed,Next Action
175,NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178,NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df.head(10)

,Date,Week,Day,Category,Topic / Task,Learning Outcome,Status,Priority,Hours Planned,Hours Spent,Resources,Deliverable,Notes,Reviewed,Next Action
0,2026-08-01,1.0,1.0,Python Fundamentals,"Object-oriented Python basics (classes, methods).",To be familiarized in python oop,Completed,NaN,2hr,1hr,https://youtu.be/rLyYb7BFgQI?si=4rjWdFSmoYcEUIrI,Documented class examples on Github,studied pythons classes andmethods,Nop,would need to learn more oop basics more than ...
1,2026-08-02,1.0,2.0,Python Fundamentals,"Python libraries intro (NumPy arrays, basic ops).",To be familiar in Python Library Numpy,Completed,NaN,4hr,2.5hrs,https://youtu.be/QUT1VHiLmmI?si=esVkANOrESh59ySI,"Numpy array manipulations (slicing, linear alg...",basic familiarity with numpy,nop,will need to understand or implement numpy in ...
2,2026-08-03,1.0,3.0,Python Fundamentals,"Pandas introduction: DataFrames, reading CSV",To be familiar in pandas,Not Started,NaN,5hr,NaN,https://youtu.be/Mdq1WWSdUtw?si=lwgel5tRZxhlcqhJ,"Load a sample dataset (Iris or\nTitanic), per...",NaN,NaN,NaN
3,2026-08-04,1.0,4.0,Algorithm,Write\nrecursive and iterative functions for c...,Brushing up recursion,Not Started,NaN,1hr,NaN,https://youtu.be/ivl5-snqul8?si=jFyy8k2glNd60W6M,do a easy and medium question in this,NaN,NaN,NaN
4,2026-08-04,1.0,4.0,SQL,"Advanced SQL (GROUP BY, aggregations, subqueries)",To be able to understand Advanced sql queries,Not Started,NaN,4hr - 6hrs,NaN,https://youtu.be/VQf0V6Wwbf4?si=M7Uwn8VnZeDFw1...,Questions in MODE ANALYTICS,NaN,NaN,NaN
5,2026-08-05,1.0,5.0,Python Fundamentals,: Basic OOP patterns in Python (inheritance),Understand diiferent patterns in python oops u...,Not Started,NaN,4hr,NaN,https://www.geeksforgeeks.org/python/inheritan...,Build a simple ML pipeline\nclass structure (...,NaN,NaN,NaN
6,2026-08-06,1.0,6.0,review/reinforce,Revisit tough Python/SQL problems.,NaN,Not Started,NaN,4hr,NaN,https://github.com/tirthajyoti/Papers-Literatu...,Solve 2-3 problems on HackerRank,NaN,NaN,NaN
7,2026-08-07,1.0,7.0,ML Fundamentals & Statics,"Descriptive stats (mean, median, variance, dis...",understand basic statitics,Not Started,NaN,4hr,NaN,https://github.com/tirthajyoti/Papers-Literatu...,Compute stats on sample datasets; visualize hi...,NaN,NaN,NaN
8,2026-08-08,2.0,1.0,ML Fundamentals & Statics,"Probability basics (Bayes’ rule, conditional p...",understand basic probability,Not Started,NaN,4hr,NaN,https://github.com/tirthajyoti/Papers-Literatu...,Solve probability\nexercises (e.g. coin flips...,NaN,NaN,NaN
9,2026-08-09,2.0,2.0,ML Fundamentals & Statics,"Central Limit Theorem, Confidence Intervals",NaN,Not Started,NaN,4hrs,NaN,https://github.com/tirthajyoti/Papers-Literatu...,Use\nsimulation (Python) to illustrate samplin...,NaN,NaN,NaN

In [20]:
df['Category']

0                                    Python Fundamentals
1                                    Python Fundamentals
2                                    Python Fundamentals
3                                              Algorithm
4                                                    SQL
5                                    Python Fundamentals
6                                       review/reinforce
7                              ML Fundamentals & Statics
8                              ML Fundamentals & Statics
9                              ML Fundamentals & Statics
10                             ML Fundamentals & Statics
11                             ML Fundamentals & Statics
12     3 days left to understand weakness and improve...
13                                                   NaN
14                                                   NaN
15                                    Core ML Algorithms
16                                    Core ML Algorithms
17                                                   NaN
18                                                   NaN
19                                                   NaN
20                                                   NaN
21                                                   NaN
22                                                   NaN
23                                                   NaN
24                                                   NaN
25                                                   NaN
26                                                   NaN
27                                                   NaN
28                                                   NaN
29                                                   NaN
30                                                   NaN
31                                                   NaN
32                                                   NaN
33                                                   NaN
34                                                   NaN
35                                                   NaN
36                                                   NaN
37                                                   NaN
38                                                   NaN
39                                                   NaN
40                                                   NaN
41                                                   NaN
42                                                   NaN
43                                                   NaN
44                                                   NaN
45                                                   NaN
46                                                   NaN
47                                                   NaN
48                                                   NaN
49                                                   NaN
50                                                   NaN
51                                                   NaN
52                                                   NaN
53                                                   NaN
54                                                   NaN
55                                                   NaN
56                                                   NaN
57                                                   NaN
58                                                   NaN
59                                                   NaN
60                                                   NaN
61                                                   NaN
62                                                   NaN
63                                                   NaN
64                                                   NaN
65                                                   NaN
66                                                   NaN
67                                                   NaN
68                                                   NaN
69                                                   NaN
70                                                   NaN
71                                                   NaN
72                                                   NaN
73                                                   NaN
74                                                   NaN
75                                                   NaN
76                                                   NaN
77                                                   NaN
78                                                   NaN
79                                                   NaN
80                                                   NaN
81                                                   NaN
82                                                   NaN
83                                                   NaN
84                                                   NaN
85                                                   NaN
86                                                   NaN
87                                                   NaN
88                                                   NaN
89                                                   NaN
90                                                   NaN
91                                                   NaN
92                                                   NaN
93                                                   NaN
94                                                   NaN
95                                                   NaN
96                                                   NaN
97                                                   NaN
98                                                   NaN
99                                                   NaN
100                                                  NaN
101                                                  NaN
102                                                  NaN
103                                                  NaN
104                                                  NaN
105                                                  NaN
106                                                  NaN
107                                                  NaN
108                                                  NaN
109                                                  NaN
110                                                  NaN
111                                                  NaN
112                                                  NaN
113                                                  NaN
114                                                  NaN
115                                                  NaN
116                                                  NaN
117                                                  NaN
118                                                  NaN
119                                                  NaN
120                                                  NaN
121                                                  NaN
122                                                  NaN
123                                                  NaN
124                                                  NaN
125                                                  NaN
126                                                  NaN
127                                                  NaN
128                                                  NaN
129                                                  NaN
130                                                  NaN
131                                                  NaN
132                                                  NaN
133                                                  NaN
134                                                  NaN
135                                                  NaN
136                                                  NaN
137                                                  NaN
138                                                  NaN
139                                                  NaN
140                                                  NaN
141                                                  NaN
142                                                  NaN
143                                                  NaN
144                                                  NaN
145                                                  NaN
146                                                  NaN
147                                                  NaN
148                                                  NaN
149                                                  NaN
150                                                  NaN
151                                                  NaN
152                                                  NaN
153                                                  NaN
154                                                  NaN
155                                                  NaN
156                                                  NaN
157                                                  NaN
158                                                  NaN
159                                                  NaN
160                                                  NaN
161                                                  NaN
162                                                  NaN
163                                                  NaN
164                                                  NaN
165                                                  NaN
166                                                  NaN
167                                                  NaN
168                                                  NaN
169                                                  NaN
170                                                  NaN
171                                                  NaN
172                                                  NaN
173                                                  NaN
174                                                  NaN
175                                                  NaN
176                                                  NaN
177                                                  NaN
178                                                  NaN
179                                                  NaN
Name: Category, dtype: str

In [26]:
df.loc[1:10]

,Date,Week,Day,Category,Topic / Task,Learning Outcome,Status,Priority,Hours Planned,Hours Spent,Resources,Deliverable,Notes,Reviewed,Next Action
1,2026-08-02,1.0,2.0,Python Fundamentals,"Python libraries intro (NumPy arrays, basic ops).",To be familiar in Python Library Numpy,Completed,NaN,4hr,2.5hrs,https://youtu.be/QUT1VHiLmmI?si=esVkANOrESh59ySI,"Numpy array manipulations (slicing, linear alg...",basic familiarity with numpy,nop,will need to understand or implement numpy in ...
2,2026-08-03,1.0,3.0,Python Fundamentals,"Pandas introduction: DataFrames, reading CSV",To be familiar in pandas,Not Started,NaN,5hr,NaN,https://youtu.be/Mdq1WWSdUtw?si=lwgel5tRZxhlcqhJ,"Load a sample dataset (Iris or\nTitanic), per...",NaN,NaN,NaN
3,2026-08-04,1.0,4.0,Algorithm,Write\nrecursive and iterative functions for c...,Brushing up recursion,Not Started,NaN,1hr,NaN,https://youtu.be/ivl5-snqul8?si=jFyy8k2glNd60W6M,do a easy and medium question in this,NaN,NaN,NaN
4,2026-08-04,1.0,4.0,SQL,"Advanced SQL (GROUP BY, aggregations, subqueries)",To be able to understand Advanced sql queries,Not Started,NaN,4hr - 6hrs,NaN,https://youtu.be/VQf0V6Wwbf4?si=M7Uwn8VnZeDFw1...,Questions in MODE ANALYTICS,NaN,NaN,NaN
5,2026-08-05,1.0,5.0,Python Fundamentals,: Basic OOP patterns in Python (inheritance),Understand diiferent patterns in python oops u...,Not Started,NaN,4hr,NaN,https://www.geeksforgeeks.org/python/inheritan...,Build a simple ML pipeline\nclass structure (...,NaN,NaN,NaN
6,2026-08-06,1.0,6.0,review/reinforce,Revisit tough Python/SQL problems.,NaN,Not Started,NaN,4hr,NaN,https://github.com/tirthajyoti/Papers-Literatu...,Solve 2-3 problems on HackerRank,NaN,NaN,NaN
7,2026-08-07,1.0,7.0,ML Fundamentals & Statics,"Descriptive stats (mean, median, variance, dis...",understand basic statitics,Not Started,NaN,4hr,NaN,https://github.com/tirthajyoti/Papers-Literatu...,Compute stats on sample datasets; visualize hi...,NaN,NaN,NaN
8,2026-08-08,2.0,1.0,ML Fundamentals & Statics,"Probability basics (Bayes’ rule, conditional p...",understand basic probability,Not Started,NaN,4hr,NaN,https://github.com/tirthajyoti/Papers-Literatu...,Solve probability\nexercises (e.g. coin flips...,NaN,NaN,NaN
9,2026-08-09,2.0,2.0,ML Fundamentals & Statics,"Central Limit Theorem, Confidence Intervals",NaN,Not Started,NaN,4hrs,NaN,https://github.com/tirthajyoti/Papers-Literatu...,Use\nsimulation (Python) to illustrate samplin...,NaN,NaN,NaN
10,2026-08-10,2.0,3.0,ML Fundamentals & Statics,"Hypothesis testing basics (t-test, chi-square)",NaN,Not Started,NaN,4hr,NaN,https://github.com/tirthajyoti/Papers-Literatu...,Apply a t-test on two small\ndatasets (Python’...,NaN,NaN,NaN

# Filtering And Ordering

## Filtering based on columns

In [27]:
df[df['Status'] == 'Completed']

,Date,Week,Day,Category,Topic / Task,Learning Outcome,Status,Priority,Hours Planned,Hours Spent,Resources,Deliverable,Notes,Reviewed,Next Action
0,2026-08-01,1.0,1.0,Python Fundamentals,"Object-oriented Python basics (classes, methods).",To be familiarized in python oop,Completed,NaN,2hr,1hr,https://youtu.be/rLyYb7BFgQI?si=4rjWdFSmoYcEUIrI,Documented class examples on Github,studied pythons classes andmethods,Nop,would need to learn more oop basics more than ...
1,2026-08-02,1.0,2.0,Python Fundamentals,"Python libraries intro (NumPy arrays, basic ops).",To be familiar in Python Library Numpy,Completed,NaN,4hr,2.5hrs,https://youtu.be/QUT1VHiLmmI?si=esVkANOrESh59ySI,"Numpy array manipulations (slicing, linear alg...",basic familiarity with numpy,nop,will need to understand or implement numpy in ...

In [28]:
specific_columns = ["Python Fundamentals","SQL"]
df[df['Category'].isin(specific_columns)]

,Date,Week,Day,Category,Topic / Task,Learning Outcome,Status,Priority,Hours Planned,Hours Spent,Resources,Deliverable,Notes,Reviewed,Next Action
0,2026-08-01,1.0,1.0,Python Fundamentals,"Object-oriented Python basics (classes, methods).",To be familiarized in python oop,Completed,NaN,2hr,1hr,https://youtu.be/rLyYb7BFgQI?si=4rjWdFSmoYcEUIrI,Documented class examples on Github,studied pythons classes andmethods,Nop,would need to learn more oop basics more than ...
1,2026-08-02,1.0,2.0,Python Fundamentals,"Python libraries intro (NumPy arrays, basic ops).",To be familiar in Python Library Numpy,Completed,NaN,4hr,2.5hrs,https://youtu.be/QUT1VHiLmmI?si=esVkANOrESh59ySI,"Numpy array manipulations (slicing, linear alg...",basic familiarity with numpy,nop,will need to understand or implement numpy in ...
2,2026-08-03,1.0,3.0,Python Fundamentals,"Pandas introduction: DataFrames, reading CSV",To be familiar in pandas,Not Started,NaN,5hr,NaN,https://youtu.be/Mdq1WWSdUtw?si=lwgel5tRZxhlcqhJ,"Load a sample dataset (Iris or\nTitanic), per...",NaN,NaN,NaN
4,2026-08-04,1.0,4.0,SQL,"Advanced SQL (GROUP BY, aggregations, subqueries)",To be able to understand Advanced sql queries,Not Started,NaN,4hr - 6hrs,NaN,https://youtu.be/VQf0V6Wwbf4?si=M7Uwn8VnZeDFw1...,Questions in MODE ANALYTICS,NaN,NaN,NaN
5,2026-08-05,1.0,5.0,Python Fundamentals,: Basic OOP patterns in Python (inheritance),Understand diiferent patterns in python oops u...,Not Started,NaN,4hr,NaN,https://www.geeksforgeeks.org/python/inheritan...,Build a simple ML pipeline\nclass structure (...,NaN,NaN,NaN

In [32]:
df[df['Category'].str.contains('ML')]

,Date,Week,Day,Category,Topic / Task,Learning Outcome,Status,Priority,Hours Planned,Hours Spent,Resources,Deliverable,Notes,Reviewed,Next Action
7,2026-08-07,1.0,7.0,ML Fundamentals & Statics,"Descriptive stats (mean, median, variance, dis...",understand basic statitics,Not Started,NaN,4hr,NaN,https://github.com/tirthajyoti/Papers-Literatu...,Compute stats on sample datasets; visualize hi...,NaN,NaN,NaN
8,2026-08-08,2.0,1.0,ML Fundamentals & Statics,"Probability basics (Bayes’ rule, conditional p...",understand basic probability,Not Started,NaN,4hr,NaN,https://github.com/tirthajyoti/Papers-Literatu...,Solve probability\nexercises (e.g. coin flips...,NaN,NaN,NaN
9,2026-08-09,2.0,2.0,ML Fundamentals & Statics,"Central Limit Theorem, Confidence Intervals",NaN,Not Started,NaN,4hrs,NaN,https://github.com/tirthajyoti/Papers-Literatu...,Use\nsimulation (Python) to illustrate samplin...,NaN,NaN,NaN
10,2026-08-10,2.0,3.0,ML Fundamentals & Statics,"Hypothesis testing basics (t-test, chi-square)",NaN,Not Started,NaN,4hr,NaN,https://github.com/tirthajyoti/Papers-Literatu...,Apply a t-test on two small\ndatasets (Python’...,NaN,NaN,NaN
11,2026-08-11,2.0,4.0,ML Fundamentals & Statics,"inear algebra refresh (vectors, matrices, dot ...",NaN,Not Started,NaN,4hr,NaN,NaN,Implement a linear\nregression “from scratch” ...,NaN,NaN,NaN
15,2026-08-15,3.0,1.0,Core ML Algorithms,Supervised learning,being able to deeply understand supervised mod...,Not Started,NaN,4hrs,NaN,https://youtu.be/VmbA0pi2cRQ?si=rP1rZ-XpYa8L8Vfp,Use scikit-learn to train a simple Linear\nReg...,NaN,NaN,NaN
16,2026-08-16,3.0,2.0,Core ML Algorithms,Classification,should understnd logistic regression and such ...,Not Started,NaN,4hrs,NaN,https://youtu.be/3giTXZbyf1Q?si=CjWYxu5a4PY83RGt,Train Logistic Regression on Iris or Titanic; ...,NaN,NaN,NaN

In [34]:
df2 = df.set_index('Date')
df2

,Week,Day,Category,Topic / Task,Learning Outcome,Status,Priority,Hours Planned,Hours Spent,Resources,Deliverable,Notes,Reviewed,Next Action
Date,,,,,,,,,,,,,,
2026-08-01,1.0,1.0,Python Fundamentals,"Object-oriented Python basics (classes, methods).",To be familiarized in python oop,Completed,NaN,2hr,1hr,https://youtu.be/rLyYb7BFgQI?si=4rjWdFSmoYcEUIrI,Documented class examples on Github,studied pythons classes andmethods,Nop,would need to learn more oop basics more than ...
2026-08-02,1.0,2.0,Python Fundamentals,"Python libraries intro (NumPy arrays, basic ops).",To be familiar in Python Library Numpy,Completed,NaN,4hr,2.5hrs,https://youtu.be/QUT1VHiLmmI?si=esVkANOrESh59ySI,"Numpy array manipulations (slicing, linear alg...",basic familiarity with numpy,nop,will need to understand or implement numpy in ...
2026-08-03,1.0,3.0,Python Fundamentals,"Pandas introduction: DataFrames, reading CSV",To be familiar in pandas,Not Started,NaN,5hr,NaN,https://youtu.be/Mdq1WWSdUtw?si=lwgel5tRZxhlcqhJ,"Load a sample dataset (Iris or\nTitanic), per...",NaN,NaN,NaN
2026-08-04,1.0,4.0,Algorithm,Write\nrecursive and iterative functions for c...,Brushing up recursion,Not Started,NaN,1hr,NaN,https://youtu.be/ivl5-snqul8?si=jFyy8k2glNd60W6M,do a easy and medium question in this,NaN,NaN,NaN
2026-08-04,1.0,4.0,SQL,"Advanced SQL (GROUP BY, aggregations, subqueries)",To be able to understand Advanced sql queries,Not Started,NaN,4hr - 6hrs,NaN,https://youtu.be/VQf0V6Wwbf4?si=M7Uwn8VnZeDFw1...,Questions in MODE ANALYTICS,NaN,NaN,NaN
2026-08-05,1.0,5.0,Python Fundamentals,: Basic OOP patterns in Python (inheritance),Understand diiferent patterns in python oops u...,Not Started,NaN,4hr,NaN,https://www.geeksforgeeks.org/python/inheritan...,Build a simple ML pipeline\nclass structure (...,NaN,NaN,NaN
2026-08-06,1.0,6.0,review/reinforce,Revisit tough Python/SQL problems.,NaN,Not Started,NaN,4hr,NaN,https://github.com/tirthajyoti/Papers-Literatu...,Solve 2-3 problems on HackerRank,NaN,NaN,NaN
2026-08-07,1.0,7.0,ML Fundamentals & Statics,"Descriptive stats (mean, median, variance, dis...",understand basic statitics,Not Started,NaN,4hr,NaN,https://github.com/tirthajyoti/Papers-Literatu...,Compute stats on sample datasets; visualize hi...,NaN,NaN,NaN
2026-08-08,2.0,1.0,ML Fundamentals & Statics,"Probability basics (Bayes’ rule, conditional p...",understand basic probability,Not Started,NaN,4hr,NaN,https://github.com/tirthajyoti/Papers-Literatu...,Solve probability\nexercises (e.g. coin flips...,NaN,NaN,NaN
2026-08-09,2.0,2.0,ML Fundamentals & Statics,"Central Limit Theorem, Confidence Intervals",NaN,Not Started,NaN,4hrs,NaN,https://github.com/tirthajyoti/Papers-Literatu...,Use\nsimulation (Python) to illustrate samplin...,NaN,NaN,NaN
2026-08-10,2.0,3.0,ML Fundamentals & Statics,"Hypothesis testing basics (t-test, chi-square)",NaN,Not Started,NaN,4hr,NaN,https://github.com/tirthajyoti/Papers-Literatu...,Apply a t-test on two small\ndatasets (Python’...,NaN,NaN,NaN
2026-08-11,2.0,4.0,ML Fundamentals & Statics,"inear algebra refresh (vectors, matrices, dot ...",NaN,Not Started,NaN,4hr,NaN,NaN,Implement a linear\nregression “from scratch” ...,NaN,NaN,NaN
2026-08-12,2.0,5.0,3 days left to understand weakness and improve...,Will change this based on the situation at tha...,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-08-13,2.0,6.0,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-08-14,2.0,7.0,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-08-15,3.0,1.0,Core ML Algorithms,Supervised learning,being able to deeply understand supervised mod...,Not Started,NaN,4hrs,NaN,https://youtu.be/VmbA0pi2cRQ?si=rP1rZ-XpYa8L8Vfp,Use scikit-learn to train a simple Linear\nReg...,NaN,NaN,NaN
2026-08-16,3.0,2.0,Core ML Algorithms,Classification,should understnd logistic regression and such ...,Not Started,NaN,4hrs,NaN,https://youtu.be/3giTXZbyf1Q?si=CjWYxu5a4PY83RGt,Train Logistic Regression on Iris or Titanic; ...,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaT,NaN,NaN,NaN,NaN,NaN,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
df2.filter(items = ['Category', 'Status'], axis = 1)

                                                     Category       Status
Date
2026-08-01                                Python Fundamentals    Completed
2026-08-02                                Python Fundamentals    Completed
2026-08-03                                Python Fundamentals  Not Started
2026-08-04                                          Algorithm  Not Started
2026-08-04                                                SQL  Not Started
2026-08-05                                Python Fundamentals  Not Started
2026-08-06                                   review/reinforce  Not Started
2026-08-07                          ML Fundamentals & Statics  Not Started
2026-08-08                          ML Fundamentals & Statics  Not Started
2026-08-09                          ML Fundamentals & Statics  Not Started
2026-08-10                          ML Fundamentals & Statics  Not Started
2026-08-11                          ML Fundamentals & Statics  Not Started
2026-08-12  3 days left to understand weakness and improve...  Not Started
2026-08-13                                                NaN  Not Started
2026-08-14                                                NaN  Not Started
2026-08-15                                 Core ML Algorithms  Not Started
2026-08-16                                 Core ML Algorithms  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started
NaT                                                       NaN  Not Started

In [43]:
df2.filter(items = ["2026-08-01"], axis = 0)

ValueError: cannot reindex on an axis with duplicate labels

## ORderby

In [46]:
df = pd.read_csv(r"C:\Users\darks\Downloads\world_population.csv")

In [47]:
df.head(2)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04

In [49]:
df[df['Rank'] < 10 ].sort_values(by = 'Rank', ascending = True)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81

# Indexing

In [ ]:
import pandas as pd

In [52]:
df = pd.read_csv(r"C:\Users\darks\Downloads\world_population.csv")
df.head(5)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [65]:
df = pd.read_csv(r"C:\Users\darks\Downloads\world_population.csv", index_col = 'Country')
df.head(4)

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00

In [66]:
df.reset_index(inplace = True)
df.head(5)

,Country,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [68]:
df.set_index('Country', inplace = True)
df.head(5)

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [71]:
df.loc['Albania']

Rank                                 138
CCA3                                 ALB
Capital                           Tirana
Continent                         Europe
2022 Population                2842321.0
2020 Population                2866849.0
2015 Population                2882481.0
2010 Population                2913399.0
2000 Population                3182021.0
1990 Population                3295066.0
1980 Population                2941651.0
1970 Population                2324731.0
Area (km²)                       28748.0
Density (per km²)                98.8702
Growth Rate                       0.9957
World Population Percentage         0.04
Name: Albania, dtype: object

In [70]:
df.iloc[1]

Rank                                 138
CCA3                                 ALB
Capital                           Tirana
Continent                         Europe
2022 Population                2842321.0
2020 Population                2866849.0
2015 Population                2882481.0
2010 Population                2913399.0
2000 Population                3182021.0
1990 Population                3295066.0
1980 Population                2941651.0
1970 Population                2324731.0
Area (km²)                       28748.0
Density (per km²)                98.8702
Growth Rate                       0.9957
World Population Percentage         0.04
Name: Albania, dtype: object

## MUlti_Indexing

In [83]:
df.reset_index(inplace = True)

In [84]:
df.head(10)

,Country,Continent,Rank,CCA3,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,Afghanistan,Asia,36,AFG,Kabul,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,Albania,Europe,138,ALB,Tirana,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,Algeria,Africa,34,DZA,Algiers,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,American Samoa,Oceania,213,ASM,Pago Pago,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,Andorra,Europe,203,AND,Andorra la Vella,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
5,Angola,Africa,42,AGO,Luanda,35588987.0,33428485.0,28127721.0,23364185.0,16394062.0,11828638.0,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
6,Anguilla,North America,224,AIA,The Valley,15857.0,15585.0,14525.0,13172.0,11047.0,8316.0,6560.0,6283.0,91.0,174.2527,1.0066,0.00
7,Antigua and Barbuda,North America,201,ATG,Saint John’s,93763.0,92664.0,89941.0,85695.0,75055.0,63328.0,64888.0,64516.0,442.0,212.1335,1.0058,0.00
8,Argentina,South America,33,ARG,Buenos Aires,45510318.0,45036032.0,43257065.0,41100123.0,37070774.0,32637657.0,28024803.0,23842803.0,2780400.0,16.3683,1.0052,0.57
9,Armenia,Asia,140,ARM,Yerevan,2780469.0,2805608.0,2878595.0,2946293.0,3168523.0,3556539.0,3135123.0,2534377.0,29743.0,93.4831,0.9962,0.03

In [85]:
df.set_index(['Continent','Country'], inplace = True)
df.head(5)

,,Rank,CCA3,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Continent,Country,,,,,,,,,,,,,,,
Asia,Afghanistan,36,AFG,Kabul,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Europe,Albania,138,ALB,Tirana,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Africa,Algeria,34,DZA,Algiers,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
Oceania,American Samoa,213,ASM,Pago Pago,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Europe,Andorra,203,AND,Andorra la Vella,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [86]:
df.sort_index(inplace = True)
df.head(10)

                                    Rank CCA3      Capital  2022 Population  \
Continent Country
Africa    Algeria                     34  DZA      Algiers       44903225.0
          Angola                      42  AGO       Luanda       35588987.0
          Benin                       77  BEN   Porto-Novo       13352864.0
          Botswana                   144  BWA     Gaborone        2630296.0
          Burkina Faso                58  BFA  Ouagadougou       22673762.0
          Burundi                     78  BDI    Bujumbura       12889576.0
          Cameroon                    53  CMR      Yaounde       27914536.0
          Cape Verde                 171  CPV        Praia         593149.0
          Central African Republic   117  CAF       Bangui        5579144.0
          Chad                        69  TCD    N'Djamena       17723315.0

                                    2020 Population  2015 Population  \
Continent Country
Africa    Algeria                        43451666.0       39543154.0
          Angola                         33428485.0       28127721.0
          Benin                          12643123.0       10932783.0
          Botswana                        2546402.0        2305171.0
          Burkina Faso                   21522626.0       18718019.0
          Burundi                        12220227.0       10727148.0
          Cameroon                       26491087.0       23012646.0
          Cape Verde                       582640.0         552166.0
          Central African Republic        5343020.0        4819333.0
          Chad                           16644701.0       14140274.0

                                    2010 Population  2000 Population  \
Continent Country
Africa    Algeria                        35856344.0       30774621.0
          Angola                         23364185.0       16394062.0
          Benin                           9445710.0        6998023.0
          Botswana                        2091664.0        1726985.0
          Burkina Faso                   16116845.0       11882888.0
          Burundi                         9126605.0        6307659.0
          Cameroon                       19878036.0       15091594.0
          Cape Verde                       521212.0         458251.0
          Central African Republic        4660067.0        3759170.0
          Chad                           11894727.0        8259137.0

                                    1990 Population  1980 Population  \
Continent Country
Africa    Algeria                        25518074.0       18739378.0
          Angola                         11828638.0        8330047.0
          Benin                           5133419.0        3833939.0
          Botswana                        1341474.0         938578.0
          Burkina Faso                    9131361.0        6932967.0
          Burundi                         5483793.0        4312834.0
          Cameroon                       11430520.0        8519891.0
          Cape Verde                       364563.0         317234.0
          Central African Republic        2809221.0        2415276.0
          Chad                            5827069.0        4408230.0

                                    1970 Population  Area (km²)  \
Continent Country
Africa    Algeria                        13795915.0   2381741.0
          Angola                          6029700.0   1246700.0
          Benin                           3023443.0    112622.0
          Botswana                         592244.0    582000.0
          Burkina Faso                    5611666.0    272967.0
          Burundi                         3497834.0     27834.0
          Cameroon                        6452787.0    475442.0
          Cape Verde                       287262.0      4033.0
          Central African Republic        2067356.0    622984.0
          Chad                            3667394.0   1284000.0

                                    Density (per km²)  Growth Rate  \
Continent Country
Africa    Algeria                             18.8531       1.0164
          Angola                              28.5466       1.0315
          Benin                              118.5635       1.0274
          Botswana                             4.5194       1.0162
          Burkina Faso                        83.0641       1.0259
          Burundi                            463.0874       1.0270
          Cameroon                            58.7128       1.0263
          Cape Verde                         147.0739       1.0089
          Central African Republic             8.9555       1.0224
          Chad                                13.8032       1.0316

                                    World Population Percentage
Continent Country
Africa    Algeria                                          0.56
          Angola                                           0.45
          Benin                                            0.17
          Botswana                                         0.03
          Burkina Faso                                     0.28
          Burundi                                          0.16
          Cameroon                                         0.35
          Cape Verde                                       0.01
          Central African Republic                         0.07
          Chad                                             0.22

In [91]:
df.loc['Asia']
## iloc cant do multi indexing

,Rank,CCA3,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,4.112877e+07,3.897223e+07,3.375350e+07,2.818967e+07,1.954298e+07,1.069480e+07,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Armenia,140,ARM,Yerevan,2.780469e+06,2.805608e+06,2.878595e+06,2.946293e+06,3.168523e+06,3.556539e+06,3135123.0,2534377.0,29743.0,93.4831,0.9962,0.03
Azerbaijan,91,AZE,Baku,1.035807e+07,NaN,9.863480e+06,9.237202e+06,8.190337e+06,7.427836e+06,6383060.0,5425317.0,86600.0,119.6082,1.0044,0.13
Bahrain,154,BHR,Manama,1.472233e+06,1.477469e+06,1.362142e+06,1.213645e+06,7.114420e+05,5.174180e+05,362595.0,222555.0,765.0,1924.4876,1.0061,0.02
Bangladesh,8,BGD,Dhaka,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
Bhutan,165,BTN,Thimphu,7.824550e+05,7.725060e+05,7.432740e+05,7.055160e+05,5.872070e+05,5.584420e+05,415257.0,298894.0,38394.0,20.3796,1.0064,0.01
Brunei,175,BRN,Bandar Seri Begawan,4.490020e+05,4.417250e+05,4.214370e+05,3.960530e+05,3.339260e+05,2.619280e+05,187921.0,133343.0,5765.0,77.8841,1.0081,0.01
Cambodia,73,KHM,Phnom Penh,1.676784e+07,1.639686e+07,1.541752e+07,1.436353e+07,1.211884e+07,8.910808e+06,6198959.0,6708525.0,181035.0,92.6221,1.0108,0.21
China,1,CHN,Beijing,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
Georgia,131,GEO,Tbilisi,3.744385e+06,3.765912e+06,3.771132e+06,NaN,NaN,NaN,NaN,NaN,69700.0,53.7214,0.9964,0.05
Hong Kong,104,HKG,Hong Kong,7.488865e+06,7.500958e+06,7.399838e+06,7.132438e+06,6.731195e+06,5.838574e+06,4978544.0,3955072.0,1104.0,6783.3922,0.9992,0.09
India,2,IND,New Delhi,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
Indonesia,4,IDN,Jakarta,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
Iran,17,IRN,Tehran,8.855057e+07,8.729019e+07,8.179084e+07,7.537386e+07,6.554438e+07,5.579363e+07,38520664.0,28449705.0,1648195.0,53.7258,1.0071,1.11
Iraq,35,IRQ,Baghdad,4.449612e+07,4.255698e+07,3.775781e+07,3.126488e+07,2.462886e+07,1.765838e+07,13653369.0,9811347.0,438317.0,101.5158,1.0221,0.56
Israel,98,ISR,Jerusalem,9.038309e+06,8.757489e+06,8.007778e+06,7.328445e+06,6.116958e+06,4.803254e+06,3744608.0,2907307.0,20770.0,435.1617,1.0155,0.11
Japan,11,JPN,Tokyo,1.239517e+08,1.252448e+08,1.272509e+08,1.281054e+08,1.268039e+08,1.236863e+08,117624196.0,105416839.0,377930.0,327.9753,0.9947,1.55
Jordan,83,JOR,Amman,1.128587e+07,1.092872e+07,9.494246e+06,6.931258e+06,5.056174e+06,3.480587e+06,2216903.0,1557374.0,89342.0,126.3221,1.0123,0.14
Kazakhstan,66,KAZ,Nursultan,1.939800e+07,1.897924e+07,1.783591e+07,1.662784e+07,1.523625e+07,1.686656e+07,14172710.0,12265305.0,2724900.0,7.1188,1.0105,0.24
Kuwait,129,KWT,Kuwait City,4.268873e+06,4.360444e+06,3.908743e+06,2.943356e+06,1.934901e+06,1.674938e+06,1493870.0,802786.0,17818.0,239.5821,1.0044,0.05
Kyrgyzstan,110,KGZ,Bishkek,6.630623e+06,6.424874e+06,5.914980e+06,5.483774e+06,4.935182e+06,4.394734e+06,3691209.0,3016384.0,199951.0,33.1612,1.0158,0.08
Laos,103,LAO,Vientiane,7.529475e+06,7.319399e+06,6.787419e+06,6.323418e+06,5.430853e+06,4.314443e+06,3297519.0,2675283.0,236800.0,31.7968,1.0141,0.09
Lebanon,119,LBN,Beirut,5.489739e+06,5.662923e+06,6.398940e+06,4.995800e+06,4.320642e+06,3.593700e+06,2963702.0,2381791.0,10452.0,525.2334,0.9816,0.07
Macau,167,MAC,Concelho de Macau,6.951680e+05,6.762830e+05,6.152390e+05,5.572970e+05,4.318960e+05,3.502270e+05,245332.0,247284.0,30.0,23172.2667,1.0125,0.01
Malaysia,45,MYS,Kuala Lumpur,3.393822e+07,3.319999e+07,3.106883e+07,NaN,NaN,1.751705e+07,13215707.0,10306508.0,330803.0,102.5934,1.0109,0.43
Maldives,174,MDV,Malé,5.237870e+05,5.144380e+05,4.355820e+05,NaN,NaN,2.249570e+05,164887.0,123243.0,300.0,1745.9567,1.0045,0.01
Mongolia,134,MNG,Ulaanbaatar,3.398366e+06,3.294335e+06,2.964749e+06,2.702520e+06,2.450979e+06,2.161433e+06,1697780.0,1293880.0,1564110.0,2.1727,1.0151,0.04
Myanmar,26,MMR,Nay Pyi Taw,5.417931e+07,5.342320e+07,5.148395e+07,4.939099e+07,4.553833e+07,4.009955e+07,33465781.0,27284112.0,676578.0,80.0784,1.0071,0.68
Nepal,49,NPL,Kathmandu,3.054758e+07,2.934863e+07,2.761032e+07,2.716157e+07,2.455950e+07,1.961653e+07,15600442.0,12501285.0,147181.0,207.5511,1.0171,0.38
North Korea,56,PRK,Pyongyang,2.606942e+07,2.586747e+07,2.525802e+07,2.468644e+07,2.336706e+07,2.079952e+07,17973650.0,14996879.0,120538.0,216.2755,1.0038,0.33
Oman,127,OMN,Muscat,4.576298e+06,4.543399e+06,4.191776e+06,2.881914e+06,2.344253e+06,1.804524e+06,1017462.0,670693.0,309500.0,14.7861,1.0123,0.06
Pakistan,5,PAK,Islamabad,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
Palestine,122,PSE,Ramallah,5.250072e+06,5.019401e+06,4.484614e+06,3.992278e+06,3.139954e+06,2.124609e+06,1453620.0,1118241.0,6220.0,844.0630,1.0227,0.07
Philippines,13,PHL,Manila,1.155590e+08,1.121910e+08,1.030314e+08,9.463670e+07,7.795822e+07,6.155890e+07,48419546.0,37435586.0,342353.0,337.5434,1.0147,1.45
Qatar,143,QAT,Doha,2.695122e+06,2.760385e+06,2.414573e+06,1.713504e+06,6.459370e+05,4.416750e+05,277450.0,118007.0,11586.0,232.6189,1.0026,0.03
Saudi Arabia,41,SAU,Riyadh,3.640882e+07,3.599711e+07,3.274985e+07,2.941193e+07,2.154739e+07,1.600476e+07,10171710.0,6106191.0,2149690.0,16.9368,1.0128,0.46
Singapore,113,SGP,Singapore,5.975689e+06,5.909869e+06,5.650018e+06,5.163590e+06,4.053602e+06,3.022209e+06,2400729.0,2061831.0,710.0,8416.4634,1.0058,0.07
South Korea,29,KOR,Seoul,5.181581e+07,5.184469e+07,5.099440e+07,4.881304e+07,4.678859e+07,4.412004e+07,38170501.0,32601143.0,100210.0,517.0722,0.9997,0.65
Sri Lanka,61,LKA,Colombo,2.183214e+07,2.171508e+07,2.133670e+07,2.066856e+07,1.877637e+07,1.720409e+07,14943645.0,12388769.0,65610.0,332.7563,1.0027,0.27
Syria,60,SYR,Damascus,2.212525e+07,2.077260e+07,1.920518e+07,2.233756e+07,1.630765e+07,1.240900e+07,8898954.0,6319199.0,185180.0,119.4797,1.0376,0.28
Taiwan,57,TWN,Taipei,2.389339e+07,2.382146e+07,2.351214e+07,2.308308e+07,2.219473e+07,2.058617e+07,18100281.0,14957870.0,36193.0,660.1662,1.0014,0.30
Tajikistan,95,TJK,Dushanbe,9.952787e+06,9.543207e+06,8.524063e+06,7.621779e+06,6.272998e+06,5.417860e+06,4045965.0,2993019.0,143100.0,69.5513,1.0208,0.12
Thailand,20,THA,Bangkok,7.169703e+07,7.147566e+07,7.029440e+07,6.827049e+07,6.306660e+07,5.522841e+07,45737753.0,NaN,513120.0,139.7276,1.0013,0.90
Timor-Leste,155,TLS,Dili,NaN,1.299995e+06,1.205813e+06,1.088486e+06,NaN,7.581060e+05,642224.0,554021.0,14874.0,90.1772,1.0154,0.02
Turkey,18,TUR,Ankara,8.534124e+07,8.413543e+07,7.964618e+07,7.319534e+07,6.411355e+07,5.432414e+07,44089069.0,35540990.0,783562.0,108.9145,1.0067,1.07
Turkmenistan,111,TKM,Ashgabat,6.430770e+06,6.250438e+06,5.766431e+06,5.267970e+06,4.569132e+06,3.720278e+06,2862903.0,2201432.0,488100.0,13.1751,1.0140,0.08
United Arab Emirates,97,ARE,Abu Dhabi,9.441129e+06,9.287289e+06,8.916899e+06,8.481771e+06,3.275333e+06,1.900151e+06,1014048.0,298084.0,83600.0,112.9322,1.0081,0.12
Uzbekistan,43,UZB,Tashkent,3.462765e+07,3.352666e+07,3.094942e+07,2.861423e+07,2.492555e+07,2.057910e+07,15947129.0,12011361.0,447400.0,77.3975,1.0160,0.43
Vietnam,16,VNM,Hanoi,9.818686e+07,9.664868e+07,9.219140e+07,8.741101e+07,7.900114e+07,6.691261e+07,52968270.0,41928849.0,331212.0,296.4472,1.0074,1.23
Yemen,46,YEM,Sanaa,3.369661e+07,3.228405e+07,2.851654e+07,2.474395e+07,1.862870e+07,1.337512e+07,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42